// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfDzHNYsn0ZK9b_jdHoNgUa1IGT4pLPPo',
    appId: '1:353278305299:web:55c716bae7cd5224c08be6',
    messagingSenderId: '353278305299',
    projectId: 'klean-b7457',
    authDomain: 'klean-b7457.firebaseapp.com',
    storageBucket: 'klean-b7457.appspot.com',
    measurementId: 'G-8Q3MD2PYNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnBKRWADeqtIfOpIP3E28ctfEXJBQootU',
    appId: '1:353278305299:android:60b4b3dff697af4ac08be6',
    messagingSenderId: '353278305299',
    projectId: 'klean-b7457',
    storageBucket: 'klean-b7457.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6aOaCsnoC3CFl36vuepV41jLhnmu1dg4',
    appId: '1:353278305299:ios:bdd00ace097d682ec08be6',
    messagingSenderId: '353278305299',
    projectId: 'klean-b7457',
    storageBucket: 'klean-b7457.appspot.com',
    iosClientId: '353278305299-acr3e3klda5b55qr06tsb8j23f8uhbet.apps.googleusercontent.com',
    iosBundleId: 'com.ewoindustry.klean',
  );
}
