part of './pages.dart';

abstract class Routes{
  static const INITIAL = '/';
  static const ONBOARDING= '/onBoarding';
  static const GETSTARTED= '/getStarted';
  static const LOGIN= '/login';
  static const SIGNUP= '/signup';
  static const PROFILEINPUT= '/profileInput';
  static const READY= '/ready';
  static const DASHBOARD= '/dashboard';
  static const WORKOUTCATEGORIES= '/workoutCategories';
  static const DIETCATEGORIES= '/dietCategories';
  static const POST = '/post';
  static const GOAL = '/goal';
  static const VIEWPROFILE = '/viewProfile';
  static const APPOINTMENT = '/appointment';
  static const NEWAPPOINTMENT = '/newAppointment';
  static const ACCOUNTSETTING = '/accountSetting';
  static const ACCOUNTEDIT = '/accountEdit';
  static const NOTIFICATION = '/Notification';
  static const SUPPORT = '/Support';
  static const TERMCONDITIONS = '/termCondition';
  static const PRIVACYPOLICY = '/Privacy';
  static const SETTING = '/setting';
  static const BODYMEASURE = '/bodyMeasure';
  static const STEPSCREEN = '/stepScreen';
  static const SLEEPSCREEN = '/sleepScreen';
  static const DIETPLAN = '/dietPlan';
  static const DIETDETAILS= '/dietDetails';
  static const DIETVIDEO= '/dietVideo';
  static const WORKDETAILS= '/workoutDetails';
  static const WORKVIDEO= '/workoutVideo';
  static const EXERCISE= '/exercise';
  static const EXERCISEVIDEO= '/exerciseVideo';
  static const WORKOUTVIDEO= '/workoutVideo';
  static const USERPROFILE= '/userProfile';
  static const MESSAGE= '/message';
  static const CHAT= '/chat';
  static const SUBSCRIBE= '/subscribe';
  static const INSTRUCTOR= '/instructor';
}